apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-share
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-share
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-share
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: ' 
                -XX:MinRAMPercentage=50 
                -XX:MaxRAMPercentage=80 
                -Dalfresco.host={{ .Values.repository.service.name }} 
                -Dalfresco.port={{ .Values.repository.service.externalPort }}
                -Dalfresco.context=alfresco 
                -Dalfresco.protocol=http '
            - name: REPO_HOST
              value: {{ .Values.repository.service.name }}
            - name: REPO_PORT
              value: "{{ .Values.repository.service.externalPort }}"
          image: {{ .Values.share.image.repository }}:{{ .Values.share.image.tag }}
          name: {{ .Release.Name }}-share
          ports:
            - containerPort: {{ .Values.share.image.internalPort }}
          readinessProbe:
            httpGet:
              path: /share
              port: {{ .Values.share.image.internalPort }}
            initialDelaySeconds: {{ .Values.share.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.share.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.share.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /share
              port: {{ .Values.share.image.internalPort }}
            initialDelaySeconds: {{ .Values.share.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.share.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.share.livenessProbe.timeoutSeconds }}
      restartPolicy: {{ .Values.share.restartPolicy }}

